"""Types for telemetry operation definitions."""

from enum import Enum


class Operation(str, Enum):
    """SDK operations identifiers for telemetry."""

    # Audit Log Operations
    AUDITLOG_LOG = "log"
    AUDITLOG_LOG_BATCH = "log_batch"
    AUDITLOG_CREATE_CLIENT = "create_client"

    # Data Anonymization Operations
    DATA_ANONYMIZATION_CREATE_CLIENT = "create_data_anonymization_client"
    DATA_ANONYMIZATION_ANONYMIZE_TEXT = "anonymize_text"
    DATA_ANONYMIZATION_ANONYMIZE_FILE = "anonymize_file"
    DATA_ANONYMIZATION_PSEUDONYMIZE_TEXT = "pseudonymize_text"
    DATA_ANONYMIZATION_PSEUDONYMIZE_FILE = "pseudonymize_file"

    # Destination Operations
    DESTINATION_GET_INSTANCE_DESTINATION = "get_instance_destination"
    DESTINATION_GET_SUBACCOUNT_DESTINATION = "get_subaccount_destination"
    DESTINATION_LIST_INSTANCE_DESTINATIONS = "list_instance_destinations"
    DESTINATION_LIST_SUBACCOUNT_DESTINATIONS = "list_subaccount_destinations"
    DESTINATION_CREATE_DESTINATION = "create_destination"
    DESTINATION_UPDATE_DESTINATION = "update_destination"
    DESTINATION_DELETE_DESTINATION = "delete_destination"
    DESTINATION_GET_DESTINATION = "get_destination"
    DESTINATION_GET_SERVICE_INSTANCE_ID = "get_service_instance_id"

    # Destination Label Operations
    DESTINATION_GET_LABELS = "get_destination_labels"
    DESTINATION_UPDATE_LABELS = "update_destination_labels"
    DESTINATION_PATCH_LABELS = "patch_destination_labels"

    # Certificate Operations
    CERTIFICATE_GET_INSTANCE_CERTIFICATE = "get_instance_certificate"
    CERTIFICATE_GET_SUBACCOUNT_CERTIFICATE = "get_subaccount_certificate"
    CERTIFICATE_LIST_INSTANCE_CERTIFICATES = "list_instance_certificates"
    CERTIFICATE_LIST_SUBACCOUNT_CERTIFICATES = "list_subaccount_certificates"
    CERTIFICATE_CREATE_CERTIFICATE = "create_certificate"
    CERTIFICATE_UPDATE_CERTIFICATE = "update_certificate"
    CERTIFICATE_DELETE_CERTIFICATE = "delete_certificate"

    # Certificate Label Operations
    CERTIFICATE_GET_LABELS = "get_certificate_labels"
    CERTIFICATE_UPDATE_LABELS = "update_certificate_labels"
    CERTIFICATE_PATCH_LABELS = "patch_certificate_labels"

    # Fragment Operations
    FRAGMENT_GET_INSTANCE_FRAGMENT = "get_instance_fragment"
    FRAGMENT_GET_SUBACCOUNT_FRAGMENT = "get_subaccount_fragment"
    FRAGMENT_LIST_INSTANCE_FRAGMENTS = "list_instance_fragments"
    FRAGMENT_LIST_SUBACCOUNT_FRAGMENTS = "list_subaccount_fragments"
    FRAGMENT_CREATE_FRAGMENT = "create_fragment"
    FRAGMENT_UPDATE_FRAGMENT = "update_fragment"
    FRAGMENT_DELETE_FRAGMENT = "delete_fragment"

    # Fragment Label Operations
    FRAGMENT_GET_LABELS = "get_fragment_labels"
    FRAGMENT_UPDATE_LABELS = "update_fragment_labels"
    FRAGMENT_PATCH_LABELS = "patch_fragment_labels"

    # Object Store Operations
    OBJECTSTORE_PUT_OBJECT = "put_object"
    OBJECTSTORE_PUT_OBJECT_FROM_FILE = "put_object_from_file"
    OBJECTSTORE_PUT_OBJECT_FROM_BYTES = "put_object_from_bytes"
    OBJECTSTORE_GET_OBJECT = "get_object"
    OBJECTSTORE_HEAD_OBJECT = "head_object"
    OBJECTSTORE_DELETE_OBJECT = "delete_object"
    OBJECTSTORE_LIST_OBJECTS = "list_objects"
    OBJECTSTORE_OBJECT_EXISTS = "object_exists"

    # Extensibility Operations
    EXTENSIBILITY_GET_EXTENSION_CAPABILITY_IMPLEMENTATION = (
        "get_extension_capability_implementation"
    )
    EXTENSIBILITY_CALL_HOOK = "call_hook"
    # ADMS — DocumentRelation Operations
    ADMS_RELATIONS_GET_ALL = "relations_get_all"
    ADMS_RELATIONS_GET = "relations_get"
    ADMS_RELATIONS_CREATE = "relations_create"
    ADMS_RELATIONS_DELETE = "relations_delete"
    ADMS_RELATIONS_GENERATE_UPLOAD_URLS = "relations_generate_upload_urls"
    ADMS_RELATIONS_COMPLETE_MULTIPART_UPLOAD = "relations_complete_multipart_upload"
    ADMS_RELATIONS_LOCK = "relations_lock"
    ADMS_RELATIONS_UNLOCK = "relations_unlock"
    ADMS_RELATIONS_CREATE_DRAFT = "relations_create_draft"
    ADMS_RELATIONS_VALIDATE_DRAFT = "relations_validate_draft"
    ADMS_RELATIONS_ACTIVATE_DRAFT = "relations_activate_draft"
    ADMS_RELATIONS_DISCARD_DRAFT = "relations_discard_draft"

    # ADMS — Document Operations
    ADMS_DOCUMENTS_GET_ALL = "documents_get_all"
    ADMS_DOCUMENTS_GET = "documents_get"
    ADMS_DOCUMENTS_GET_DOWNLOAD_URL = "documents_get_download_url"
    ADMS_DOCUMENTS_UPDATE = "documents_update"
    ADMS_DOCUMENTS_RESTORE_CONTENT_VERSION = "documents_restore_content_version"
    ADMS_DOCUMENTS_DELETE_CONTENT_VERSION = "documents_delete_content_version"

    # ADMS — Job Operations
    ADMS_JOBS_START_ZIP_DOWNLOAD = "jobs_start_zip_download"
    ADMS_JOBS_START_DELETE_USER_DATA = "jobs_start_delete_user_data"
    ADMS_JOBS_GET_STATUS = "jobs_get_status"

    # ADMS — Configuration Operations
    ADMS_CONFIG_GET_ALL_ALLOWED_DOMAINS = "config_get_all_allowed_domains"
    ADMS_CONFIG_CREATE_ALLOWED_DOMAIN = "config_create_allowed_domain"
    ADMS_CONFIG_DELETE_ALLOWED_DOMAIN = "config_delete_allowed_domain"
    ADMS_CONFIG_GET_ALL_DOCUMENT_TYPES = "config_get_all_document_types"
    ADMS_CONFIG_CREATE_DOCUMENT_TYPE = "config_create_document_type"
    ADMS_CONFIG_DELETE_DOCUMENT_TYPE = "config_delete_document_type"
    ADMS_CONFIG_GET_ALL_BUSINESS_OBJECT_TYPES = "config_get_all_business_object_types"
    ADMS_CONFIG_CREATE_BUSINESS_OBJECT_TYPE = "config_create_business_object_type"
    ADMS_CONFIG_DELETE_BUSINESS_OBJECT_TYPE = "config_delete_business_object_type"
    ADMS_CONFIG_GET_ALL_DOCTYPE_BOTYPE_MAPS = "config_get_all_doctype_botype_maps"
    ADMS_CONFIG_CREATE_DOCTYPE_BOTYPE_MAP = "config_create_doctype_botype_map"
    ADMS_CONFIG_GET_DOCTYPE_BOTYPE_MAP = "config_get_doctype_botype_map"
    ADMS_CONFIG_DELETE_DOCTYPE_BOTYPE_MAP = "config_delete_doctype_botype_map"
    ADMS_CONFIG_GET_ALLOWED_DOMAIN = "config_get_allowed_domain"
    ADMS_CONFIG_UPDATE_ALLOWED_DOMAIN = "config_update_allowed_domain"
    ADMS_CONFIG_GET_DOCUMENT_TYPE = "config_get_document_type"
    ADMS_CONFIG_UPDATE_DOCUMENT_TYPE = "config_update_document_type"
    ADMS_CONFIG_GET_BUSINESS_OBJECT_TYPE = "config_get_business_object_type"
    ADMS_CONFIG_UPDATE_BUSINESS_OBJECT_TYPE = "config_update_business_object_type"
    # ADMS — new DocumentService actions
    ADMS_RELATIONS_DELETE_BO_NODE = "relations_delete_bo_node"
    ADMS_CHANGELOG_GET_ALL = "changelog_get_all"
    ADMS_BO_CHANGELOG_GET_ALL = "bo_changelog_get_all"
    # ADMS — new ConfigurationService entities
    ADMS_CONFIG_MARK_DEFAULT = "config_mark_default"
    ADMS_CONFIG_GET_ALL_FILE_EXT_POLICIES = "config_get_all_file_ext_policies"
    ADMS_CONFIG_CREATE_FILE_EXT_POLICY = "config_create_file_ext_policy"
    ADMS_CONFIG_GET_FILE_EXT_POLICY = "config_get_file_ext_policy"
    ADMS_CONFIG_DELETE_FILE_EXT_POLICY = "config_delete_file_ext_policy"
    ADMS_CONFIG_GET_ALL_APP_TENANTS = "config_get_all_app_tenants"
    ADMS_CONFIG_CREATE_APP_TENANT = "config_create_app_tenant"
    ADMS_CONFIG_GET_APP_TENANT = "config_get_app_tenant"
    ADMS_CONFIG_DELETE_APP_TENANT = "config_delete_app_tenant"

    # AI Core Operations
    AICORE_SET_CONFIG = "set_aicore_config"
    AICORE_AUTO_INSTRUMENT = "auto_instrument"
    AICORE_SET_FILTERING = "set_filtering"
    AICORE_DISABLE_FILTERING = "disable_filtering"

    # Print Operations
    PRINT_LIST_QUEUES = "list_queues"
    PRINT_CREATE_QUEUE = "create_queue"
    PRINT_GET_PROFILES = "get_print_profiles"
    PRINT_UPLOAD_DOCUMENT = "upload_document"
    PRINT_CREATE_TASK = "create_print_task"
    PRINT_CREATE_CLIENT = "print_create_client"

    # DMS Operations
    DMS_ONBOARD_REPOSITORY = "onboard_repository"
    DMS_GET_REPOSITORY = "get_repository"
    DMS_GET_ALL_REPOSITORIES = "get_all_repositories"
    DMS_UPDATE_REPOSITORY = "update_repository"
    DMS_DELETE_REPOSITORY = "delete_repository"
    DMS_CREATE_CONFIG = "create_config"
    DMS_GET_CONFIGS = "get_configs"
    DMS_UPDATE_CONFIG = "update_config"
    DMS_DELETE_CONFIG = "delete_config"

    # DMS CMIS Operations
    # Prefixed with "cmis_" to distinguish from other modules (e.g.
    # ObjectStore also has "get_object" / "delete_object") and to avoid
    # Python enum aliasing on duplicate values.
    DMS_CREATE_FOLDER = "cmis_create_folder"
    DMS_CREATE_DOCUMENT = "cmis_create_document"
    DMS_CHECK_OUT = "cmis_check_out"
    DMS_CHECK_IN = "cmis_check_in"
    DMS_CANCEL_CHECK_OUT = "cmis_cancel_check_out"
    DMS_APPLY_ACL = "cmis_apply_acl"
    DMS_GET_OBJECT = "cmis_get_object"
    DMS_GET_CONTENT = "cmis_get_content"
    DMS_UPDATE_PROPERTIES = "cmis_update_properties"
    DMS_GET_CHILDREN = "cmis_get_children"
    DMS_DELETE_OBJECT = "cmis_delete_object"
    DMS_RESTORE_OBJECT = "cmis_restore_object"
    DMS_APPEND_CONTENT_STREAM = "cmis_append_content_stream"
    DMS_CMIS_QUERY = "cmis_query"

    # Agent Gateway Operations
    AGENTGATEWAY_LIST_MCP_TOOLS = "list_mcp_tools"
    AGENTGATEWAY_CALL_MCP_TOOL = "call_mcp_tool"
    AGENTGATEWAY_GET_SYSTEM_AUTH = "get_system_auth"
    AGENTGATEWAY_GET_USER_AUTH = "get_user_auth"
    AGENTGATEWAY_LIST_AGENT_CARDS = "list_agent_cards"
    AGENTGATEWAY_GET_IAS_CLIENT_ID = "get_ias_client_id"

    # DPI NG Consent Operations
    DPI_NG_CONSENT_CREATE_CLIENT = "consent_create_client"
    # ConsentService
    DPI_NG_CONSENT_LIST_CONSENTS = "consent_list_consents"
    DPI_NG_CONSENT_GET_CONSENT = "consent_get_consent"
    DPI_NG_CONSENT_DELETE_CONSENT = "consent_delete_consent"
    DPI_NG_CONSENT_CREATE_CONSENT_FROM_TEMPLATE = "consent_create_consent_from_template"
    DPI_NG_CONSENT_WITHDRAW_CONSENT = "consent_withdraw_consent"
    DPI_NG_CONSENT_TERMINATE_CONSENT = "consent_terminate_consent"
    DPI_NG_CONSENT_CHECK_CONSENT_EXISTS = "consent_check_consent_exists"
    # ConsentPurposeService
    DPI_NG_CONSENT_LIST_PURPOSES = "consent_list_purposes"
    DPI_NG_CONSENT_GET_PURPOSE = "consent_get_purpose"
    DPI_NG_CONSENT_CREATE_PURPOSE = "consent_create_purpose"
    DPI_NG_CONSENT_UPDATE_PURPOSE = "consent_update_purpose"
    DPI_NG_CONSENT_DELETE_PURPOSE = "consent_delete_purpose"
    DPI_NG_CONSENT_SET_PURPOSE_ACTIVE = "consent_set_purpose_active"
    DPI_NG_CONSENT_SET_PURPOSE_INACTIVE = "consent_set_purpose_inactive"
    DPI_NG_CONSENT_LIST_PURPOSE_TEXTS = "consent_list_purpose_texts"
    DPI_NG_CONSENT_GET_PURPOSE_TEXT = "consent_get_purpose_text"
    DPI_NG_CONSENT_CREATE_PURPOSE_TEXT = "consent_create_purpose_text"
    DPI_NG_CONSENT_UPDATE_PURPOSE_TEXT = "consent_update_purpose_text"
    DPI_NG_CONSENT_DELETE_PURPOSE_TEXT = "consent_delete_purpose_text"
    # ConsentTemplateService
    DPI_NG_CONSENT_LIST_TEMPLATES = "consent_list_templates"
    DPI_NG_CONSENT_GET_TEMPLATE = "consent_get_template"
    DPI_NG_CONSENT_CREATE_TEMPLATE = "consent_create_template"
    DPI_NG_CONSENT_UPDATE_TEMPLATE = "consent_update_template"
    DPI_NG_CONSENT_DELETE_TEMPLATE = "consent_delete_template"
    DPI_NG_CONSENT_SET_TEMPLATE_ACTIVE = "consent_set_template_active"
    DPI_NG_CONSENT_SET_TEMPLATE_INACTIVE = "consent_set_template_inactive"
    DPI_NG_CONSENT_LIST_TEMPLATE_TEXTS = "consent_list_template_texts"
    DPI_NG_CONSENT_GET_TEMPLATE_TEXT = "consent_get_template_text"
    DPI_NG_CONSENT_CREATE_TEMPLATE_TEXT = "consent_create_template_text"
    DPI_NG_CONSENT_UPDATE_TEMPLATE_TEXT = "consent_update_template_text"
    DPI_NG_CONSENT_DELETE_TEMPLATE_TEXT = "consent_delete_template_text"
    DPI_NG_CONSENT_LIST_THIRD_PARTY_PERS_DATA = "consent_list_third_party_pers_data"
    DPI_NG_CONSENT_GET_THIRD_PARTY_PERS_DATA = "consent_get_third_party_pers_data"
    DPI_NG_CONSENT_CREATE_THIRD_PARTY_PERS_DATA = "consent_create_third_party_pers_data"
    DPI_NG_CONSENT_UPDATE_THIRD_PARTY_PERS_DATA = "consent_update_third_party_pers_data"
    DPI_NG_CONSENT_DELETE_THIRD_PARTY_PERS_DATA = "consent_delete_third_party_pers_data"
    # ConsentRetentionService
    DPI_NG_CONSENT_LIST_RULES = "consent_list_rules"
    DPI_NG_CONSENT_GET_RULE = "consent_get_rule"
    DPI_NG_CONSENT_CREATE_RULE = "consent_create_rule"
    DPI_NG_CONSENT_UPDATE_RULE = "consent_update_rule"
    DPI_NG_CONSENT_DELETE_RULE = "consent_delete_rule"
    DPI_NG_CONSENT_SET_RULE_ACTIVE = "consent_set_rule_active"
    DPI_NG_CONSENT_SET_RULE_INACTIVE = "consent_set_rule_inactive"
    # ConsentConfigurationService
    DPI_NG_CONSENT_LIST_THIRD_PARTIES = "consent_list_third_parties"
    DPI_NG_CONSENT_GET_THIRD_PARTY = "consent_get_third_party"
    DPI_NG_CONSENT_CREATE_THIRD_PARTY = "consent_create_third_party"
    DPI_NG_CONSENT_UPDATE_THIRD_PARTY = "consent_update_third_party"
    DPI_NG_CONSENT_DELETE_THIRD_PARTY = "consent_delete_third_party"
    DPI_NG_CONSENT_LIST_JURISDICTIONS = "consent_list_jurisdictions"
    DPI_NG_CONSENT_GET_JURISDICTION = "consent_get_jurisdiction"
    DPI_NG_CONSENT_CREATE_JURISDICTION = "consent_create_jurisdiction"
    DPI_NG_CONSENT_UPDATE_JURISDICTION = "consent_update_jurisdiction"
    DPI_NG_CONSENT_DELETE_JURISDICTION = "consent_delete_jurisdiction"
    DPI_NG_CONSENT_LIST_JURISDICTION_TEXTS = "consent_list_jurisdiction_texts"
    DPI_NG_CONSENT_CREATE_JURISDICTION_TEXT = "consent_create_jurisdiction_text"
    DPI_NG_CONSENT_UPDATE_JURISDICTION_TEXT = "consent_update_jurisdiction_text"
    DPI_NG_CONSENT_DELETE_JURISDICTION_TEXT = "consent_delete_jurisdiction_text"
    DPI_NG_CONSENT_LIST_LANGUAGES = "consent_list_languages"
    DPI_NG_CONSENT_GET_LANGUAGE = "consent_get_language"
    DPI_NG_CONSENT_LIST_LANGUAGE_DESCRIPTIONS = "consent_list_language_descriptions"
    DPI_NG_CONSENT_CREATE_LANGUAGE_DESCRIPTION = "consent_create_language_description"
    DPI_NG_CONSENT_UPDATE_LANGUAGE_DESCRIPTION = "consent_update_language_description"
    DPI_NG_CONSENT_DELETE_LANGUAGE_DESCRIPTION = "consent_delete_language_description"
    DPI_NG_CONSENT_LIST_SOURCE_INFOS = "consent_list_source_infos"
    DPI_NG_CONSENT_GET_SOURCE_INFO = "consent_get_source_info"
    DPI_NG_CONSENT_CREATE_SOURCE_INFO = "consent_create_source_info"
    DPI_NG_CONSENT_UPDATE_SOURCE_INFO = "consent_update_source_info"
    DPI_NG_CONSENT_DELETE_SOURCE_INFO = "consent_delete_source_info"
    DPI_NG_CONSENT_LIST_CONTROLLERS = "consent_list_controllers"
    DPI_NG_CONSENT_GET_CONTROLLER = "consent_get_controller"
    DPI_NG_CONSENT_CREATE_CONTROLLER = "consent_create_controller"
    DPI_NG_CONSENT_UPDATE_CONTROLLER = "consent_update_controller"
    DPI_NG_CONSENT_DELETE_CONTROLLER = "consent_delete_controller"
    DPI_NG_CONSENT_LIST_DATA_SUBJECT_TYPES = "consent_list_data_subject_types"
    DPI_NG_CONSENT_GET_DATA_SUBJECT_TYPE = "consent_get_data_subject_type"
    DPI_NG_CONSENT_CREATE_DATA_SUBJECT_TYPE = "consent_create_data_subject_type"
    DPI_NG_CONSENT_UPDATE_DATA_SUBJECT_TYPE = "consent_update_data_subject_type"
    DPI_NG_CONSENT_DELETE_DATA_SUBJECT_TYPE = "consent_delete_data_subject_type"
    DPI_NG_CONSENT_LIST_APPLICATIONS = "consent_list_applications"
    DPI_NG_CONSENT_GET_APPLICATION = "consent_get_application"
    DPI_NG_CONSENT_CREATE_APPLICATION = "consent_create_application"
    DPI_NG_CONSENT_UPDATE_APPLICATION = "consent_update_application"
    DPI_NG_CONSENT_DELETE_APPLICATION = "consent_delete_application"
    DPI_NG_CONSENT_LIST_MASTER_DATA_SOURCES = "consent_list_master_data_sources"
    DPI_NG_CONSENT_GET_MASTER_DATA_SOURCE = "consent_get_master_data_source"
    DPI_NG_CONSENT_CREATE_MASTER_DATA_SOURCE = "consent_create_master_data_source"
    DPI_NG_CONSENT_UPDATE_MASTER_DATA_SOURCE = "consent_update_master_data_source"
    DPI_NG_CONSENT_DELETE_MASTER_DATA_SOURCE = "consent_delete_master_data_source"
    DPI_NG_CONSENT_LIST_OUTBOUND_CHANNEL_TYPES = "consent_list_outbound_channel_types"
    DPI_NG_CONSENT_GET_OUTBOUND_CHANNEL_TYPE = "consent_get_outbound_channel_type"
    DPI_NG_CONSENT_CREATE_OUTBOUND_CHANNEL_TYPE = "consent_create_outbound_channel_type"
    DPI_NG_CONSENT_UPDATE_OUTBOUND_CHANNEL_TYPE = "consent_update_outbound_channel_type"
    DPI_NG_CONSENT_DELETE_OUTBOUND_CHANNEL_TYPE = "consent_delete_outbound_channel_type"

    # Agent Memory Operations
    AGENT_MEMORY_ADD_MEMORY = "add_memory"
    AGENT_MEMORY_GET_MEMORY = "get_memory"
    AGENT_MEMORY_UPDATE_MEMORY = "update_memory"
    AGENT_MEMORY_DELETE_MEMORY = "delete_memory"
    AGENT_MEMORY_LIST_MEMORIES = "list_memories"
    AGENT_MEMORY_COUNT_MEMORIES = "count_memories"
    AGENT_MEMORY_SEARCH_MEMORIES = "search_memories"
    AGENT_MEMORY_ADD_MESSAGE = "add_message"
    AGENT_MEMORY_GET_MESSAGE = "get_message"
    AGENT_MEMORY_DELETE_MESSAGE = "delete_message"
    AGENT_MEMORY_LIST_MESSAGES = "list_messages"
    AGENT_MEMORY_GET_RETENTION_CONFIG = "get_retention_config"
    AGENT_MEMORY_UPDATE_RETENTION_CONFIG = "update_retention_config"

    def __str__(self) -> str:
        return self.value
